'use strict';
const assert=require('node:assert/strict');
const p=require('./ui/presentation.js');
let passed=0;
function test(name,run){run();passed++;console.log('PASS: '+name);}
test('sentence-case category names',()=>{assert.equal(p.categoryLabel('garden_tools'),'Garden tools');assert.equal(p.categoryLabel('sports_leisure'),'Sports leisure');assert.equal(p.categoryLabel('watches_gifts'),'Watches & gifts');});
test('capital M and lower-case k across money axes',()=>{assert.equal(p.compact(1250000),'1.25M');assert.equal(p.compact(250000),'250k');assert.equal(p.compact(-50000),'-50k');assert.equal(p.compact(0),'0');});
test('round tick spacing for the known peak',()=>{const a=p.niceTicks(0,987765.37);assert.equal(a.step,250000);assert.deepEqual(a.values,[0,250000,500000,750000,1000000,1250000]);});
test('negative and zero extents are valid',()=>{for(const [a,b]of [[-100,20],[0,0],[-100,-50],[0,0.5]]){const t=p.niceTicks(a,b);assert(t.low<=Math.min(0,a));assert(t.high>=Math.max(0,b));assert(t.values.includes(0));}});
test('trend headline and peak use selected evidence',()=>{const a=p.trendFinding({reference:{delivered_merchandise_value:'13181027.13',delivered_orders:96211},rows:[{purchase_month:'2017-11',delivered_merchandise_value:'987765.37'},{purchase_month:'2018-08',delivered_merchandise_value:'838576.64'}]});assert.equal(a.headline,'R$ 13.18M across 96,211 delivered orders.');assert(a.finding.includes('Nov 2017'));assert(!a.finding.includes('softening'));});
test('a different range has a different peak and total',()=>{const a=p.trendFinding({reference:{delivered_merchandise_value:'30',delivered_orders:3},rows:[{purchase_month:'2018-01',delivered_merchandise_value:'10'},{purchase_month:'2018-02',delivered_merchandise_value:'20'}]});assert(a.finding.includes('Feb 2018'));assert(a.headline.includes('R$ 30'));assert.equal(a.peakValue,'20');});
test('equal and tied peaks are disclosed',()=>{assert(p.trendFinding({reference:{delivered_merchandise_value:'20',delivered_orders:2},rows:[{purchase_month:'2017-01',delivered_merchandise_value:'10'},{purchase_month:'2017-02',delivered_merchandise_value:'10'}]}).finding.includes('same merchandise value'));});
test('both contribution directions are selected without mutating evidence',()=>{const data=[{category_label:'negative_a',change_value:'-5'},{category_label:'negative_b',change_value:'-10'},{category_label:'positive_a',change_value:'8'},{category_label:'positive_b',change_value:'20'},{category_label:'zero',change_value:'0'}];const before=JSON.stringify(data),groups=p.contributions(data);assert.equal(groups.negative[0].category_label,'negative_b');assert.equal(groups.positive[0].category_label,'positive_b');assert.equal(JSON.stringify(data),before);});
test('one-sided and empty contributions do not invent positives',()=>{assert.equal(p.contributions([{change_value:'-1',category_label:'a'}]).positive.length,0);assert.equal(p.contributions([]).negative.length,0);});
test('clarification and refusal do not imply queried data',()=>{assert.equal(p.resultStatus({ai_review:{verdict:'PASS'},evidence:[]}),'No data queried');assert.equal(p.resultStatus({ai_review:{verdict:'PASS'},evidence:[{tool:'search_metric_dictionary',result:{matches:[]}}]}),'Documentation searched');});
test('numerical and recorded statuses remain accurate',()=>{assert.equal(p.resultStatus({ai_review:{verdict:'PASS'},evidence:[{tool:'get_monthly_trend',result:{rows:[]}}]}),'Analysis reviewed');assert.equal(p.resultStatus({evidence:[{tool:'get_monthly_trend',result:{error:'failed'}}]}),'No numerical result');assert.equal(p.resultStatus({is_demo:true}),'Recorded example');});
console.log(`${passed} presentation checks passed; no network or API calls.`);
