/* Pure display helpers. Source identifiers and evidence values stay unchanged. */
(function(root){
  'use strict';
  function compact(value,places=2){const n=Number(value);if(!Number.isFinite(n))return 'Unavailable';const size=Math.abs(n),scale=size>=1e6?1e6:size>=1000?1000:1,suffix=scale===1e6?'M':scale===1000?'k':'';return (n/scale).toFixed(places).replace(/(\.\d*?[1-9])0+$|\.0+$/,'$1')+suffix;}
  function niceTicks(minimum,maximum,target=4){let lo=Math.min(0,Number(minimum)),hi=Math.max(0,Number(maximum));if(!Number.isFinite(lo)||!Number.isFinite(hi))throw Error('Invalid chart extent');if(lo===hi)hi=lo+1;const raw=(hi-lo)/target,base=10**Math.floor(Math.log10(raw)),fraction=raw/base;const multiplier=[1,2,2.5,5,10].find(n=>n>=fraction-1e-12),step=multiplier*base;const low=Math.floor((lo<0?lo*1.08:lo)/step)*step,high=Math.ceil((hi>0?hi*1.08:hi)/step)*step;const values=[];for(let n=0;n<=Math.round((high-low)/step);n++)values.push(Number((low+n*step).toPrecision(12)));return {low,high,step,values};}
  function categoryLabel(label){const names={bed_bath_table:'Bed, bath & table',watches_gifts:'Watches & gifts',health_beauty:'Health & beauty',computers_accessories:'Computer accessories',pc_gamer:'PC gamer'};if(names[label])return names[label];const text=String(label).replaceAll('_',' ').toLowerCase();return text.charAt(0).toUpperCase()+text.slice(1);}
  function monthLabel(month){const value=String(month).slice(0,7);if(!/^\d{4}-\d{2}$/.test(value))return String(month);const [year,m]=value.split('-');return ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][Number(m)-1]+' '+year;}
  function trendFinding(data){const rows=data.rows||[],reference=data.reference;if(!rows.length||!reference)return null;const values=rows.map(row=>Number(row.delivered_merchandise_value));if(values.some(n=>!Number.isFinite(n)))return null;const peak=Math.max(...values),peaks=rows.filter(row=>Number(row.delivered_merchandise_value)===peak);const count=Number(reference.delivered_orders),total=Number(reference.delivered_merchandise_value);if(!Number.isSafeInteger(count)||count<0||!Number.isFinite(total))return null;const headline='R$ '+compact(total)+' across '+new Intl.NumberFormat('en-US').format(count)+' delivered orders.';const finding=peaks.length===rows.length&&rows.length>1?'All reported months have the same merchandise value.':'Highest monthly merchandise value: '+monthLabel(peaks[0].purchase_month)+(peaks.length>1?' (shared by '+peaks.length+' months)':'')+'.';return {headline,finding,peakMonth:peaks[0].purchase_month,peakValue:peaks[0].delivered_merchandise_value,total:reference.delivered_merchandise_value,orders:reference.delivered_orders};}
  function contributions(categories){const rows=(categories||[]).filter(row=>Number.isFinite(Number(row.change_value)));const tie=(a,b)=>String(a.category_label).localeCompare(String(b.category_label));return {negative:rows.filter(r=>Number(r.change_value)<0).sort((a,b)=>Number(a.change_value)-Number(b.change_value)||tie(a,b)).slice(0,3),positive:rows.filter(r=>Number(r.change_value)>0).sort((a,b)=>Number(b.change_value)-Number(a.change_value)||tie(a,b)).slice(0,3)};}
  function resultStatus(result){if(result.is_demo)return 'Recorded example';const events=result.evidence||[],numeric=new Set(['get_monthly_metrics','compare_months','get_category_changes','decompose_merchandise_change','get_monthly_trend','get_category_performance','get_seller_performance','get_state_delivery']);if(events.some(e=>numeric.has(e.tool)&&e.result&&!e.result.error))return result.ai_review?.verdict==='PASS'?'Analysis reviewed':'Inspect verification';if(events.some(e=>e.tool==='search_metric_dictionary'))return 'Documentation searched';if(events.some(e=>numeric.has(e.tool)))return 'No numerical result';return 'No data queried';}
  const helpers={compact,niceTicks,categoryLabel,monthLabel,trendFinding,contributions,resultStatus};
  if(typeof module!=='undefined'&&module.exports)module.exports=helpers;
  root.CausynPresentation=helpers;
})(typeof globalThis!=='undefined'?globalThis:this);
